# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to move'), ('S', 'Second player to move'), ('W', 'First player won'), ('L', 'Second player won'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
